language: ruby
script:
  - bundle exec rake test:all
  - bundle exec rake rubocop
rvm:
  - 2.2.1
  - 2.2.0
  - 2.1.0
  - 2.0.0

notifications:
  slack:
    secure: CUYqzHxxls0Kc+s/MiKtjJvxQltXu/BpJYKooxQ3dGYKB3USnQCdOx0roE4rjUlClJwicZJxd4nBeiG66zRnVfoOC317qt9Y9vcFuxTjEzG/Okzez4RdfB6UGsqqiJifu7bf/GJMHIQYcgc59508SngCWDYcceKhr962Gz+M/ls=
